#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9

# Values captured here are remembered for the next version's submission, not for
# the app — the extension itself reads no environment at all.
ENV_FILE=".amo-submission.env"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"
VERSION="$(node -p "require('./manifest.json').version")"
ZIP="web-ext-artifacts/dopamine-toll-${VERSION}.zip"

banner "Publish Dopamine Toll ${VERSION} to addons.mozilla.org"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Pre-flight — build and lint the package"
say "Nothing manual here. We verify the package before it ever reaches Mozilla."
say ""
step "Running the test suite…"
npm test >/dev/null 2>&1 && say "  ✓ tests pass" || { warn "tests FAILED — run 'npm test' and fix before submitting"; exit 1; }
step "Building the store ZIP…"
npm run build >/dev/null 2>&1 && say "  ✓ built $ZIP" || { warn "build failed — run 'npm run build'"; exit 1; }
step "Running the AMO linter (this is the same one the reviewer's tooling runs)…"
say ""
npm run lint:amo 2>&1 | tail -n 20 || true
say ""
note "Expected warnings: BACKGROUND_SERVICE_WORKER_IGNORED (intentional, see docs/adr/0001)"
note "and 3 UNSAFE_VAR_ASSIGNMENT hits (explained in docs/amo-reviewer-notes.md)."
warn "If you see any ERRORS above, stop and fix them — AMO will reject the upload."
pause "Linter output look right? Press Enter to continue"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Android — validate on a real device"
say "gecko_android is in the manifest, so this build claims Android support."
say "Reviewers reject add-ons that are unusable on mobile. Verify it yourself first."
say ""
if adb devices | grep -qw "device"; then
  say "✓ adb sees a device."
  step "This opens Dopamine Toll on your phone in a temporary Firefox profile."
  if confirm "Launch it on the device now?"; then
    say ""
    note "Firefox for Android must be installed, with Remote debugging via USB enabled"
    note "in its Settings. Ctrl-C the runner when you're done poking at it."
    npx --yes web-ext@latest run -t firefox-android --source-dir=. || true
  fi
else
  warn "No device found by adb."
  step "Plug the phone in, enable USB debugging, and accept the pairing prompt."
  step "Then re-run this wizard, or test later with:"
  note "  npx --yes web-ext@latest run -t firefox-android --source-dir=."
fi
say ""
say "Critical paths to walk on the phone: the gate appears on a listed site; the"
say "countdown runs; both buttons work; the popup and settings page are usable at"
say "phone width."
say ""
warn "If Android is NOT usable, remove 'gecko_android' from manifest.json and"
warn "re-run this wizard — you can add Android support in a later version."
if ! confirm "Did Android behave well enough to ship?"; then
  say ""
  say "Stopping here. Remove the gecko_android key, run 'npm test', and start again."
  exit 0
fi

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Mozilla account"
say "AMO submissions are tied to a Mozilla account. Create one if you don't have it."
open_url "https://accounts.firefox.com/signup"
step "Sign up (or sign in if you already have a Mozilla account)."
step "Verify the email — AMO will not let you submit before the address is confirmed."
step "Turn on two-factor authentication when prompted. Mozilla requires 2FA for"
step "  add-on developers; you cannot submit without it."
ask AMO_ACCOUNT_EMAIL "Which email did you use?"
write_env AMO_ACCOUNT_EMAIL "$AMO_ACCOUNT_EMAIL"
pause "Account created, verified, and 2FA on? Press Enter"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Developer Hub — accept the agreement"
open_url "https://addons.mozilla.org/developers/"
step "Click 'Submit Your First Add-on' (or 'Submit a New Add-on')."
step "Read and accept the Firefox Add-on Distribution Agreement and the review policies."
note "This is a one-time gate on the account, not per add-on."
pause "Agreement accepted? Press Enter"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Upload the package"
say "Uploading $ZIP"
open_url "https://addons.mozilla.org/developers/addon/submit/distribution"
step "Choose 'On this site' — the listed, publicly distributed option."
note "'On your own' means self-distribution: signed but not listed on AMO. Not what we want."
step "Upload the ZIP. Its absolute path is:"
note "  $REPO_ROOT/$ZIP"
step "Wait for the automatic validation to finish. Warnings are fine; errors are not."
step "When asked which applications to support, confirm both Firefox and"
step "  Firefox for Android are checked — the manifest already declares both."
step "Answer NO when asked whether you need to submit source code: this add-on"
step "  ships unminified, unobfuscated vanilla JavaScript."
pause "Package accepted by validation? Press Enter"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Listing — name, summary, description"
say "The copy lives in STORE_DESCRIPTION.md. Open it beside the browser."
say "AMO allows 250 characters of summary (Chrome allowed 132), so the existing"
say "text fits without trimming."
say ""
step "Name: Dopamine Toll"
step "Add-on URL slug: pick carefully — it is PERMANENT and becomes the listing URL."
step "Summary: the 'appDesc' string from _locales/en/messages.json."
step "Description: the English block from STORE_DESCRIPTION.md."
step "Categories: choose up to two. 'Privacy & Security' and 'Other' fit this add-on."
step "Support email: eraserheadsoftware@gmail.com"
step "Support site / homepage: https://github.com/dankhael/DopamineToll"
ask AMO_ADDON_SLUG "What slug did you choose?"
write_env AMO_ADDON_SLUG "$AMO_ADDON_SLUG"
pause "Listing basics filled in? Press Enter"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Listing — license, privacy, screenshots"
step "License: select Mozilla Public License 2.0 — it matches the LICENSE file in the repo."
step "Privacy policy: paste the contents of PRIVACY.md, or link to"
note "  https://github.com/dankhael/DopamineToll/blob/main/PRIVACY.md"
say ""
warn "AMO takes only ONE set of screenshots for the whole listing — image captions"
warn "are localizable, the images are not. Upload the English renders."
step "Upload from: design_handoff_store_screenshots/png/screenshot-0*-en.png"
note "Missing? Regenerate: cd design_handoff_store_screenshots/tools && npm run render"
step "Write a caption for each screenshot."
pause "License, policy, and screenshots done? Press Enter"

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Localize the listing and submit"
say "AMO localizes name, summary, description, and screenshot captions."
say "STORE_DESCRIPTION.md carries all six: en, de, fr, pt_BR, ja, zh_CN."
step "For each locale, use the language selector on the listing form and paste"
step "  the matching block from STORE_DESCRIPTION.md."
say ""
step "Finally, 'Notes for Reviewers': paste everything below the '---' in"
step "  docs/amo-reviewer-notes.md. This is where <all_urls> and the remaining"
step "  innerHTML uses get explained — do not skip it."
say ""
if confirm "Open the reviewer notes in your pager now?"; then
  "${PAGER:-less}" docs/amo-reviewer-notes.md || true
fi
step "Submit the version for review."
pause "Submitted? Press Enter"

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "After submitting"
ask AMO_ADDON_URL "Paste the public listing URL (addons.mozilla.org/…):"
write_env AMO_ADDON_URL "$AMO_ADDON_URL"
say ""
say "What happens next:"
note "  - Review times vary from hours to days. Watch the account email."
note "  - Reviewers may ask questions; answer in the Developer Hub, not by email."
say ""
warn "Do not forget the other half of this release:"
step "The same 1.2.0 code must go to the Chrome Web Store — the store copy and"
step "  PRIVACY.md changed for both stores, not just Firefox."
step "Upload the same $ZIP at:"
note "  https://chrome.google.com/webstore/devconsole"
say ""
step "Then record the AMO link in README.md and STORE_DESCRIPTION.md."

finish
